FROM alpine
#Create a docker image from alpine

MAINTAINER mlmpofu
#One of the best practices in Dockerfiles to put the person that owns the Dockerfile

RUN apk update && apk upgrade && apk add vim
#Installing vim and updating it

CMD ["vim"]
#THis is to launch vim editor
